`ifndef AJARDSP_CONFIG_V_
`define AJARDSP_CONFIG_V_

`define AJARDSP_CONFIG_ENABLE_ACCRF_BYPASS
//`undef AJARDSP_CONFIG_ENABLE_ACCRF_BYPASS

`define AJARDSP_CONFIG_ENABLE_PTRRF_BYPASS
//`undef AJARDSP_CONFIG_ENABLE_PTRRF_BYPASS

`define AJARDSP_CONFIG_ENABLE_PRED_BYPASS
//`undef AJARDSP_CONFIG_ENABLE_PRED_BYPASS

`define AJARDSP_CONFIG_ACC_GUARD_BITS 8

`define AJARDSP_CONFIG_EXT_BOOT

`endif
